### ISSUE TITLE
build script="make all" no longer works

### ISSUE THREAD

**Issue by MarkWieczorek** [fortran-lang/fpm#341] opened 2021-01-21 15:25 UTC
About a year ago, I was able to compile of complex project of mine using a pre-existing Makefile. After finding out about the environment variables `$BUILD_DIR` and `$FC`, this was pretty easy, I only needed to specify the following:

```
[library]
build-script = "make all F95=$FC LIBPATH=$BUILD_DIR MODPATH=$BUILD_DIR"
```

However, I just updated to the latest alpha version (0.1.3), and this does't seem to work anymore: the makefile is not being executed and instead fpm is trying to compile the file in the src directory.

Is there a way to specify using a prexisting makefile, or a way pass optional variables to the Makefile?

**Comment by milancurcic** [comment] 2021-01-21 15:41
Are you using the Haskell (fpm-haskell-0.1.3*) or Fortran (fpm-0.1.3*) client? This is not yet implemented in the latter.

**Comment by ivan-pi** [comment] 2021-01-21 15:42
Hello @MarkWieczorek,

note the `build-script` was an "experimental" feature available in the bootstrap fpm (the Haskell version). In the meantime a Fortran version of fpm has been built. You can check the [manifest reference](https://fpm.fortran-lang.org/page/Manifest.html#library-configuration) to see what is available.

Executables for the Haskell version can be found in the assets section of the latest [release](https://github.com/fortran-lang/fpm/releases/tag/v0.1.3).

A specification for the `build-script` feature is currently under discussion in https://github.com/fortran-lang/fpm/issues/249.

**Comment by MarkWieczorek** [comment] 2021-01-21 15:50
I'm using the Fortran client. Should the Haskell version be the default? or is the plan to make the Fortran version the default?

So, I am guessing the answer is: *Check back later*

That's fine with me. However, I just want to emphasize that if you want old, or complicated projects to work with fpm, eventually, you will need to pass environment variables to the makefile!

**Comment by ivan-pi** [comment] 2021-01-21 15:53
The Fortran version is (and will remain) the default. The build script is just one of the features which hasn't been implemented yet in the Fortran version.

**Comment by LKedward** [comment] 2021-01-22 10:01
Thanks for the feedback @MarkWieczorek. Support for a custom build script is one of two (big) priority items remaining in our [milestone ](https://github.com/fortran-lang/fpm/milestone/1). I'll close this issue as a duplicate of #219.

**Closed by LKedward** 2021-01-22 10:01 UTC
