### ISSUE TITLE
FPM creating multiple directories in build

### ISSUE THREAD

**Issue by jacobwilliams** [fortran-lang/fpm#916] opened 2023-05-28 17:59 UTC
### Description

It seems like FPM is now creating multiple subdirectories in `build`. I think this behavior changed at some point? For example, when I run `fpm test --profile debug --flag -coverage` I get two `gfortran_*` directories:

![image](https://github.com/fortran-lang/fpm/assets/6483379/4df88f0a-31de-469f-86f5-c662c7c23cb4)

In my CI, I have lines like this:

```yml
lcov --capture --initial --base-directory . --directory build/gfortran_*/ --output-file ${{ env.COV_DIR }}/coverage.base
```

So, that is now broken since it's no longer just a single directory. This used to work, so I think something has changed (I have dozens of repos with this).

Any ideas on how to get the one that I need (the one where the compile happens and the coverage files are generated)?

### Expected Behaviour

Was expecting only one `build/gfortran_*` directory.

### Version of fpm

fortran-lang/setup-fpm@v5

### Platform and Architecture

ubuntu

**Comment by perazz** [comment] 2023-05-28 20:04
What I see is that the directory hash is defined by the build flags: 

https://github.com/fortran-lang/fpm/blame/a3d689fb6f319afb09987bda1d0e59f66d71e9e0/src/fpm_targets.f90#L975

so I guess there will be as many folders as build flag combinations for the different targets

**Comment by awvwgk** [comment] 2023-05-29 11:07
This behavior is intended, since different files can have different arguments, especially since preprocessor flags and Fortran options can now be defined on per project basis.

If `lcov` can take multiple directories as input you can probably adopt the command line options. Better would be to have fpm learn about coverage tools and provide first class support for them.

**Comment by perazz** [comment] 2023-06-10 14:31
Should we close this as intended behavior?

**Comment by jacobwilliams** [comment] 2023-06-11 01:22
Yes can close. 

My CI solution is to do this:

mv ./build/gfortran_*/*/* ${{ env.COV_DIR }}

**Closed** 2023-06-11 06:17 UTC
