### ISSUE TITLE
fpm not preprocessing main.f90 with `--flag -cpp`

### ISSUE THREAD

**Issue by rouson** [fortran-lang/fpm#791] opened 2022-11-03 02:39 UTC
### Description

Using `fpm build --flag -cpp` to compile a simple `app/main.f90` containing a C preprocessor directive fails:
```
$ fpm new fpm-issue
$ cd fpm-issue/app
$ vim main.f90
$ cat main.f90 
program main
#ifdef NONEXISTENT
 use nonexistent
#endif
  implicit none
end program
$ fpm build --flag -cpp
$ <ERROR>*cmd_build*:target error:Unable to find source for module dependency: "nonexistent" used by "app/main.f90"
STOP 1
$ fpm --version
Version:     0.6.0, alpha
```
Compiling with `gfortran -cpp main.f90` works.

### Expected Behaviour

I expect `--flag -cpp` to cause `fpm` to use `gfortran -cpp` to compile.

### Version of fpm

0.6.0

### Platform and Architecture

macOS/Intel

**Comment by awvwgk** [comment] 2022-11-03 05:33
Duplicate of https://github.com/fortran-lang/fpm/issues/773

**Closed by awvwgk** 2022-11-03 05:33 UTC
Labels: bug

**Comment by urbanjost** [comment] 2022-11-03 06:35
It is passing the -cpp flag. It is the fact that when scanning the code for module dependencies it looks for USE statements unconditionally. It has actually not gotten to the compilation.

So it is still a problem, but not quite what you describe. If you had something not being parsed for by fpm itelse in the #if/#endif region it would work, for example.  

It would require preprocessing all the input files and only scanning the files afterward to avoid this problem robustly; and the predefined variables the compiler users are not the same in all cases as those used by a straight call to the preprocessor, which would be a harder issue to hit, but also a problem. 

Not an elegant solution, but perhaps if a # is found in a file a missing file could be ignored or only be a warning; which except in the rare case where a file starts with a # character that is a continuation of the previous line this would help with cpp (but not all preprocessors, which do not all start directives with a # in column 1). 

If the module does not exist because it is external you are in luck. The USE statement will be ignored
if in your fpm.module file you have
```text[build]
external-modules = ["nonexistent"]
```
then it is assumed the "nonexistent" module is not built by your package, and you want to have that line
in your fpm.toml file anyway.

Another bug is that only "use " and "use::" are looked for, so if you use "use,non-intrinsic:: nonexistent"
or "use,intrinsic:: nonexistent"  it would get to the compiler, but also would not potentially build in the right order if the module really is built by the package; so I would not recommend taking advantage of that.

Same for using macros so the "use " string is not part of the line, which would also trick it.

So hopefully, you really are only conditionally using an external module, and using the correct syntax in the fpm.toml file to indicate it is external correctly resolves the problem.

Preprocessing all the files and putting the output files into the build/ directory would be a big change and would require careful consideration of how the compilers search for include files so I do not think that change would be coming any time soon.

**Comment by rouson** [comment] 2022-11-07 18:18
@urbanjost when you wrote "fpm.module," was that a typographical error?   If so, then I think your suggested workaround will work for us because the dependency in question is not built by our project so we'll try putting `external-modules = ["nonexistent"]` in our fpm.toml file and see if that works around the issue.

**Comment by urbanjost** [comment] 2022-11-07 23:25
Yes. should have been "fpm.toml".  I cleaned up the original post a bit; I was composing this while it was being closed and did not realize it showed up. I think the discussion linked to above when this was marked as a duplicate basically says to do the same thing.
