### ISSUE TITLE
[build] Nonportable usage in fpm-0.10.1.F90

### ISSUE THREAD

**Issue by klausler** [fortran-lang/fpm#1031] opened 2024-05-01 15:30 UTC
### Description

In fpm-0.10.1.F90 there are some instances of nonportable non-conforming Fortran usage.

* At 27433, `type(toml_error), allocatable :: toml_error` uses the name of a derived type in the host scope to declare a variable of the same name in the local scope.

* At 28256 and many sites after, the code attempts to define DEFERRED procedure bindings, but they are PRIVATE to their original module.  It is valid to override a PRIVATE binding in another module (although many compilers fail to prevent the override from affecting usage in the original module), but not in the case of a DEFERRED binding.

### Expected Behaviour

Compilation by most Fortran compilers

### Version of fpm

fpm-0.10.1

### Platform and Architecture

n/a

**Comment by perazz** [comment] 2024-05-01 16:24
Duplicate of #1012, all these issues have been solved in #1011 #1013 and will appear in the next release.

**Comment by perazz** [comment] 2024-05-02 05:55
Will close this for now - please reopen if new issue arise, thank you.

**Closed by perazz** 2024-05-02 05:55 UTC
Labels: bug, duplicate
